program test_rand

    use cudafor
    use mrand

    implicit none
    integer:: pfnt, np, i, j
    integer:: tPB = 256
    real(8),allocatable,device:: rnum_de(:,:)
    real(8),allocatable,pinned:: rnum_h(:,:)
    real(8):: mean,var

    pfnt = 400
    np = tPB
    allocate(rnum_de(pfnt,np),h(np))
    allocate(rnum_h(pfnt,np))

    call createRand_test<<<1,tPB>>>()
    call callRand_test<<<1,tPB>>>(rnum_de,pfnt)
    rnum_h = rnum_de

    !do i = 1, np

        mean = sum(rnum_h)/pfnt/tPB
        var = sum((rnum_h-mean)**2)/(pfnt*tPB-1)

    !end do

    write(*,*) mean
    write(*,*) var

end program